### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [floatboat/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - e.g., https://code.visualstudio.com/ , https://sdacs.ucsd.edu/~icc/index.php , etc.
- [x] All relevant code examples written with backticks (```)
  - please format terminal commands as code (e.g., cd, ls, pwd, etc.)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - the method in the screenshot is not running the java program in the remote computer
  - for reference, this is what we're looking for: Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by floatboat** [comment]
Hi,

It seems that my lab report has links that automatically go to a website if clicked. Am I supposed to put it in the "[Link] (http://a.com)" format? 

Thank you!

**Comment by floatboat** [comment]
Also, would I need to add more "commands" for the Remotely Connecting part, or could I just put the ones I have in the backticks?

**Comment by floatboat** [comment]
Also, it seems that I did edit my program locally, then ran it remotely. I've updated my lab report with some edits, but the images are the same - could you check it out?

**Comment by farnaf** [comment]
Hi there!
- Please put the links in the "[Link] (http://a.com)" format
- No need for more commands, you can just format the commands you already have on your report as backticks for the second rubric item
- I think the method in the screenshot is still not running the java program on the server. You successfully copy the file over, but I think you're running it on your local computer because the output of the program is giving information about your local environment (e.g., Windows, thuan, etc.) - your current method needs just a small addition of a `ssh [your_15L_account]` so the program runs on the server remotely

**Comment by farnaf** [comment]
FYI, the images are not loading here: https://floatboat.github.io/cse15l-lab-reports/lab-report-1-week-2.html 

I think [img_name].png should be changed to [img_name].PNG in your code!

I saw the images in your repo and updated your grade to 1/1, so no need for regrade request(:
